"""
   Descp: Use this file in order to isolate your app text

   Created on: 21-feb-2020

   Copyright 2020-2021 Youssef 'FRYoussef' El Faqir El Rhazoui
        <f.r.youssef@hotmail.com>
"""

TEXT: dict = {
    'abs_fail': 'Absolute majority rejection',
    'abs_pass': 'Absolute majority approval',
    'acknowledgements': ' and chain-community projects were funded by the European Research Council and The Spanish Ministry of Science and Innovation',
    'active_users_title': 'Active reputation holders',
    'all_orgs': 'All DAOs',
    'app_title': 'DAO-Analyzer',
    'boost': 'Rate of boosted proposals that were approved',
    'boost_fail': 'Boosted rejections',
    'boost_pass': 'Boosted approvals',
    'cc_image_url': 'https://i.creativecommons.org/l/by/4.0/88x31.png',
    'cc_license_text': 'This site is licensed under a Creative Commons Attribution 4.0 International License',
    'cc_url': 'https://creativecommons.org/licenses/by/4.0/',
    'dao_selector_title': 'Select your DAO: ',
    'default_amount': 'NAN',
    'different_stakers_title': 'Different stakers',
    'different_voters_title': 'Different voters',
    'downstakes': 'Downstakes',
    'erc_image_url': 'https://erc.europa.eu/sites/default/files/LOGO_ERC-FLAG_EU_.png',
    'erc_url': 'https://erc.europa.eu/',
    'github': 'Follow us on GitHub: ',
    'github_url': 'https://github.com/Grasia/dao-analyzer',
    'gpl_image_url': 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/93/GPLv3_Logo.svg/1200px-GPLv3_Logo.svg.png',
    'gpl_license_text': 'The code is licensed under GPLv3',
    'gpl_url': 'https://www.gnu.org/licenses/gpl-3.0.en.html',
    'graph_amount': '{}: {}',
    'graph_subtitle': '{:.2f}% month over month',
    'new_proposals_title': 'New proposals',
    'new_users_title': 'New reputation holders',
    'no_data': 'No data',
    'no_data_selected': 'There\'s no DAO selected',
    'not_boost': 'Rate of non-boosted proposals that were rejected',
    'p2p_models': 'P2P Models',
    'p2p_models_url': 'https://p2pmodels.eu/',
    'pane_css_prefix': 'pane',
    'proposal_boost_outcome_title': 'Closed proposal\'s outcome',
    'proposal_boost_succ_rate_title': 'Success rate of the stakes by type',
    'proposal_outcome_majority_title': 'Closed proposal\'s majority outcome',
    'proposal_title': 'Proposals',
    'proposal_total_succ_rate_title': 'Total success rate of the stakes',
    'queue_fail': 'Non-boosted rejections',
    'queue_pass': 'Non-boosted approvals',
    'rel_fail': 'Relative majority rejection',
    'rep_holder_title': 'Reputation holders',
    'rel_pass': 'Relative majority approval',
    'spanish_ministry_image_url': 'https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcRfq3CJzLUtY8NUahJOUBdn35aAMHMhqcihyA&usqp=CAU',
    'spanish_ministry_url': 'https://www.ciencia.gob.es/',
    'stake_title': 'Stakes',
    'total_stakes_option_title': 'Total stakes option',
    'total_stakes_title': 'Total stakes',
    'total_votes_option_title': 'Total votes option',
    'total_votes_title': 'Total votes',
    'upstakes': 'Upstakes',
    'votes_against': 'Votes against',
    'votes_for': 'Votes for',
    'vote_title': 'Votes',
}
