name: Check cache_scripts continuation mode
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
    paths:
      - 'cache_scripts/**'
jobs:
  check_continue:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@master
    - name: Getting datawarehouse cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dw
        path: |
          ./datawarehouse*
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install package
      run: pip install -e .
    - name: Run verify-scripts
      run: ./scripts/checkContinue.sh
    - name: Upload datawarehouse artifact
      uses: actions/upload-artifact@v3
      with:
        name: datawarehouse
        path: datawarehouse