name: Publish Docker images
on: 
  push:
    branches:
      - main
      - develop
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@3.04
      env:
        POPULATE_CACHE: 0
      with:
        name: grasia/dao-analyzer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: POPULATE_CACHE
        tag_semver: true
    - run: echo "::set-env name=TAG_CACHED::$(echo ${GITHUB_REF#refs/heads/}-cached)"
    - name: Publish to Docker Hub with cache
      uses: elgohr/Publish-Docker-Github-Action@3.04
      env:
        POPULATE_CACHE: 1
      with:
        name: grasia/dao-analyzer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: POPULATE_CACHE
        tags: "${{ env.TAG_CACHED }}"