name: Publish Docker images
on: 
  workflow_dispatch:
  workflow_run:
    workflows: 
      - Check cache_scripts continuation mode
    branches:
      - master
      - develop
    types:
      - completed
      - requested
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.9.1
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@master
    - name: Getting datawarehouse cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dw
        path: |
          ./datawarehouse
    - name: Publish to Docker Hub
      uses: elgohr/Publish-Docker-Github-Action@3.04
      with:
        name: grasia/dao-analyzer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_semver: true
    - name: "Get cached tag name"
      run: |
        branch=${GITHUB_REF#refs/heads/}
        [[ "$branch" = "master" ]] && branch=latest
        echo "::set-output name=tag_cached::$branch-cached"
      id: cached_envs
    - name: Publish to Docker Hub with cache
      uses: elgohr/Publish-Docker-Github-Action@3.04
      env:
        POPULATE_CACHE: 1
      with:
        name: grasia/dao-analyzer
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        buildargs: POPULATE_CACHE
        tags: ${{ steps.cached_envs.outputs.tag_cached }}
